import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import Location from "@/components/Logos/Location";
import Phone from "@/components/Logos/Phone";
import Email from "@/components/Logos/Email";
import Instagram from "@/components/Logos/Instagram";
import Button from "@/components/Button/Button";
import QuestionBox from "@/components/QuestionBox/QuestionBox";
import questions from "public/data/aboutQuestion";
import reviews from "public/data/clientReviews";
import ReviewBox from "@/components/ReviewBox/ReviewBox";
import ClientBox from "@/components/ClientBox/ClientBox";

function ContactBoxes({ children, text, onClick }) {
  return (
    <div className={styles.contactBoxContainer}>
      {children}
      <span style={{ marginLeft: "1rem" }}>
        {!text
          ? "Duis ea esse ullamco est eiusmod dolor reprehenderit elit ad aute nostrud."
          : text}
      </span>
    </div>
  );
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Home - The Formante Recording Services</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <Navbar home />
        {/* Close container */}
        <div className={styles.content}>
          <section className={`${styles.introduction} ${styles.section} `}>
            <div className={styles.introLeft}>
              <h1>THE FORMANTE</h1>
              <h3>Recording Services</h3>
              <p>
                Sunt esse proident id nulla amet labore amet irure in sint est
                esse excepteur. Lorem in et fugiat eu sit. Ullamco incididunt
                culpa mollit aliquip duis nostrud voluptate excepteur sunt
                mollit eiusmod nisi nostrud voluptate.
              </p>
              <div className={styles.buttons}>
                <Button>BUTTON</Button>
                <Button>BUTTON</Button>
              </div>
            </div>
            <div className={styles.introRight}>
              <div className={styles.imageContainer}>
                <Image
                  src="/images/home_v2.png"
                  width={587}
                  height={475}
                  alt="home"
                  className={styles.image}
                />
              </div>
            </div>
          </section>
          <section className={`${styles.section} ${styles.about}`}>
            <div className={styles.aboutHeading}>About me</div>
            <p className={styles.aboutPara}>
              Adipisicing dolor duis id sunt quis.
            </p>
            <div className={styles.aboutQuestions}>
              {questions.map((question) => {
                return (
                  <QuestionBox
                    key={question.id}
                    question={question.question}
                    answer={question.answer}
                    icon={question.icon}
                  />
                );
              })}
            </div>
          </section>
          <section className={`${styles.section} ${styles.services}`}></section>
          <section className={`${styles.section} ${styles.clientele}`}>
            <div className={styles.clienteleHeading}>
              <h1>Clientele</h1>
            </div>
            <div className={styles.clients}>
              <ClientBox />
              <ClientBox />
              <ClientBox />
              <ClientBox />
            </div>
            <Button styles={{ margin: "auto", marginTop: "50px" }}>
              All Clients
            </Button>
          </section>
          <section className={`${styles.section} ${styles.reviews}`}>
            <h1>Reviews</h1>
            <h3>Labore et id amet dolor quis nisi ipsum.</h3>
            <div className={styles.reviewsContainer}>
              {reviews.map((service, index) => (
                <ReviewBox
                  comment={service.comment}
                  rating={service.rating}
                  services={service.services}
                  website={service.website}
                  key={index}
                  styling={{ margin: "2rem auto" }}
                />
              ))}
              <Button width={"50%"} styles={{ margin: "0 auto" }}>
                Show more reviews
              </Button>
            </div>
          </section>
          <section className={`${styles.section} ${styles.contact}`}>
            <div className={styles.contactLeftSection}>
              <ContactBoxes text="136 University Blvd, Sydney, Nova Scotia - B1M 1A2">
                <Location />
              </ContactBoxes>
              <ContactBoxes text={"+1 782-882-5427"}>
                <Phone />
              </ContactBoxes>
              <ContactBoxes text="formantemusic@gmail.com">
                <Email />
              </ContactBoxes>
              <ContactBoxes text={"theformante"}>
                <Instagram height="31px" width="31px" />
              </ContactBoxes>
            </div>
            <div className={styles.contactRightSection}>
              <div className={styles.contactDetails}>
                <h1>Get In Touch</h1>
                <p>Lorem ipsum dolor sit amet consectetur.</p>
                <form onSubmit={() => console.log("it work")}>
                  <div style={{ display: "flex", marginBottom: "1rem" }}>
                    <label htmlFor="firstName">
                      First name
                      <input type="text" name="firstName" />
                    </label>
                    <label htmlFor="lastName">
                      Last name
                      <input
                        type="text"
                        name="lastName"
                        style={{ width: "100%" }}
                      />
                    </label>
                  </div>
                  <div style={{ display: "flex", marginBottom: "1rem" }}>
                    <label htmlFor="email">
                      E-mail
                      <input type="email" name="email" />
                    </label>
                    <label htmlFor="phoneNumber">
                      Phone number
                      <input
                        type="text"
                        name="phoneNumber"
                        style={{ width: "100%" }}
                      />
                    </label>
                  </div>
                  <label htmlFor="message">Message</label>
                  <textarea name="firstName" />
                  <Button onClick={"submit"} width={"100%"}>
                    SUBMIT
                  </Button>
                </form>
              </div>
              <div className={styles.contactImage}>
                <Image
                  src={"/images/contact_character_v2.png"}
                  alt={"contact_character_v2"}
                  width={300}
                  height={300}
                  className={styles.image}
                />
              </div>
            </div>
          </section>
        </div>
        <Footer />
      </div>
    </>
  );
}
