import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import Button from "@/components/Button/Button";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Home - The Formante Recording Services</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <Navbar home />
        {/* Close container */}
        <div className={styles.content}>
          <section className={`${styles.introduction} ${styles.section} `}>
            <div className={styles.introLeft}>
              <h1>THE FORMANTE</h1>
              <h3>Recording Services</h3>
              <p>
                Sunt esse proident id nulla amet labore amet irure in sint est
                esse excepteur. Lorem in et fugiat eu sit. Ullamco incididunt
                culpa mollit aliquip duis nostrud voluptate excepteur sunt
                mollit eiusmod nisi nostrud voluptate.
              </p>
              <div className={styles.buttons}>
                <Button>BUTTON</Button>
                <Button>BUTTON</Button>
              </div>
            </div>
            <div className={styles.introRight}>
              <div className={styles.imageContainer}>
                <Image
                  src="/images/home_v2.png"
                  width={587}
                  height={475}
                  alt="home"
                  className={styles.image}
                />
              </div>
            </div>
          </section>
          <section className={`${styles.section} ${styles.about}`}></section>
          <section className={`${styles.section} ${styles.services}`}></section>
          <section
            className={`${styles.section} ${styles.clientele}`}
          ></section>
          <section className={`${styles.section} ${styles.reviews}`}></section>
          <section className={`${styles.section} ${styles.contact}`}></section>
        </div>
        <Footer />
      </div>{" "}
    </>
  );
}
